version: "3.9"

services:
    app:
        container_name: web-tagsdev
        image: ghcr.io/mcbtaguiad/web-tagsdev-jekyll:v1.2.0
        build:
            context: .
            dockerfile: Dockerfile.apache
        restart: always
        ports:
            - "8000:80"
