title: TagsDev
author: Mark Taguiad
email: marktaguiad@tagsdev.xyz
url: https://tagsdev.xyz
description: > 
  Mark Taguiad Blog Maybe

linkedin: mark-christian-taguiad
github: mcbtaguiad # Add your Github handle
instagram: mark.tags
strava: 123512498

permalink: /:slug.html

favicon: "./favicon.ico" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: expanded

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Google Analytics
google_analytics: G-XCHH9NNNBX
  